# Generated by Django 5.1.3 on 2024-11-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waste",
            name="category",
            field=models.CharField(
                choices=[
                    ("biodegradable", "Biodegradable"),
                    ("non_biodegradable", "Non_biodegradable"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="waste",
            name="weight",
            field=models.FloatField(help_text="kgs"),
        ),
        migrations.DeleteModel(
            name="WasteCategory",
        ),
    ]
